server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
